version: '3.8'

services:
  app:
    image: ghcr.io/flovalle1/digitales-modulhandbuch/app:latest
    ports:
      - "3000:3000"
    depends_on:
      migrate:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nextjs_db
    restart: always

  migrate:
    image: ghcr.io/flovalle1/digitales-modulhandbuch/app:latest
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c"]
    command: npx prisma migrate deploy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nextjs_db
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: