version: '4'

services:
  app:
    image: ghcr.io/flovalle1/digitales-modulhandbuch/app:latest
    pull_policy: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  cronservice:
    image: ghcr.io/flovalle1/digitales-modulhandbuch/cronservice:latest
    environment:
      - WEBHOOK_URL=${POSTGRES_PASSWORD}/api/updatesemester
      - API_KEY=${CRONJOB_API_KEY}
    restart: always

volumes:
  postgres_data:

