version: '3.8'

services:
  app:
    image: ghcr.io/flovalle1/digitales-modulhandbuch/app:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c"]
    command: |
      npx prisma migrate deploy && npm start
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nextjs_db
    restart: always

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: