name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-nextjs-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push Next.js App
      run: |
        # Build app service
        docker build -t digitales-modulhandbuch-app:latest .
        
        # Tag and push app service image
        docker tag digitales-modulhandbuch-app:latest ghcr.io/${{ github.repository }}/app:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/app:${{ github.sha }}
        docker tag digitales-modulhandbuch-app:latest ghcr.io/${{ github.repository }}/app:latest
        docker push ghcr.io/${{ github.repository }}/app:latest

    - name : Build and Push Cronservice  
      run: |
        docker build -t cronservice:latest cronjob/
        
        # Tag and push cronservice image
        docker tag cronservice:latest ghcr.io/${{ github.repository }}/cronservice:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/cronservice:${{ github.sha }}
        docker tag cronservice:latest ghcr.io/${{ github.repository }}/cronservice:latest
        docker push ghcr.io/${{ github.repository }}/cronservice:latest
