name: Build and Upload Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push Docker Compose Services
      run: |
        # Get the list of services from docker-compose.yml
        SERVICES=$(docker compose config --services | tr '\n' ' ')
        
        # Build and push each service
        for service in $SERVICES; do
          docker compose build $service

          IMAGE_ID=$(docker compose images -q $service)
          if [ -z "$IMAGE_ID" ]; then
            echo "Failed to get image ID for service $service"
            exit 1
          fi

          docker tag $IMAGE_ID ghcr.io/${{ github.repository }}/$service:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/$service:${{ github.sha }}
        done