name: Build and Upload Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Compose Services
      run: |
        docker compose build

    - name: Save Docker Images to files
      run: |
        mkdir -p docker-images
        SERVICES=$(docker compose config --services)
        for service in $SERVICES; do
          docker save $(docker compose ps -q $service) -o docker-images/$service.tar
        done

    - name: Upload Docker Images as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docker-images
        path: docker-images/*.tar
